### ISSUE TITLE
Cant get it to run

### ISSUE THREAD

**Issue by saitoh183** [hslatman/caddy-crowdsec-bouncer#16]
trying to get this to work but i keep getting this error when i add `order crowdsec first`

`Error during parsing: crowdsec is not a registered directive`

if i comment it out then i get the error

`Error: adapting config using caddyfile: /etc/caddy/Caddyfile:47: unrecognized directive: crowdsec`

My DockerFile:
```
ARG VERSION=2

FROM caddy:${VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/hslatman/caddy-crowdsec-bouncer/crowdsec \
    --with github.com/RussellLuo/caddy-ext/layer4 \
    --with github.com/mholt/caddy-l4

FROM caddy:${VERSION}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

My Caddyfile:
https://pastebin.com/vQ1y2VFz

Is there a way to see if the plugin was installed? Also Caddy is running as Docker

**Comment by hslatman** [comment]
The plugin is installed with 'github.com/hslatman/caddy-crowdsec-bouncer/http' instead of 'github.com/hslatman/caddy-crowdsec-bouncer/crowdsec'. You specified the latter. It's imported by the 'http' one.
