### ISSUE TITLE
Error: loading initial config: loading new config: loading http app module: provision http: server server1: setting up route handlers: route 0: loading handler modules: position 0: loading module 'crowdsec': unknown module: http.handlers.crowdsec

### ISSUE THREAD

**Issue by asucrews** [hslatman/caddy-crowdsec-bouncer#21]
When trying the demo, i get this below error on current verzion of go and caddy.  not sure what happening

Error: loading initial config: loading new config: loading http app module: provision http: server server1: setting up route handlers: route 0: loading handler modules: position 0: loading module 'crowdsec': unknown module: http.handlers.crowdsec

**Comment by hslatman** [comment]
Hey @asucrews, haven't checked the Caddy code yet, but this sounds like Caddy was built without the module included? Are you sure it's  included in your build?

**Comment by asucrews** [comment]
Yes xcaddy with http and layer4.  When I get time I will copy the statement I used.

**Comment by Emeric-hub** [comment]
Hi, It seems you didn't build the module with xcaddy...

**Comment by hslatman** [comment]
Closing this, as the solution is to build Caddy with `github.com/hslatman/caddy-crowdsec-bouncer/http` and/or `github.com/hslatman/caddy-crowdsec-bouncer/layer4`.
