### ISSUE TITLE
Request: add support for {env.*} placeholder

### ISSUE THREAD

**Issue by doums** [hslatman/caddy-crowdsec-bouncer#25]
Hi, when using `Caddyfile`, it seems like the crowdsec module configuration does not support `{env.*}` placeholder.
Considering there is a `.env` file containing `CROWDSEC_BOUNCER_KEY` variable:

```Caddyfile
  crowdsec {
    api_url http://host.docker.internal:8060
    api_key {env.CROWDSEC_BOUNCER_KEY}
    ticker_interval 15s
    # disable_streaming
    # enable_hard_fails
  }
```

Will result with a `403 - API error: access forbidden` because crowdsec module is not providing the api_key from env variable as expected.

```
{"level":"error","ts":1699643960.8473945,"logger":"crowdsec","msg":"API error: access forbidden","address":"http://host.docker.internal:8060/","error":"API error: access forbidden"}
```

It could be tricky for the user to understand what's going on. The current solution is to hard-code de key in the Caddyfile which is not great for security reason.

**Comment by hslatman** [comment]
Sounds nice. Going to do this next 😄

**Comment by hslatman** [comment]
@doums when I try it with `{$CROWDSEC_BOUNCER_KEY}` as an actual environment variable, it does work. I think the `{env.CROWDSEC_BOUNCER_KEY}` would work in a Docker container, and that using a `{env.<value>` depends on the environment it's used it? 

The fact that you use a `.env` file doesn't change that the secret actually has to come from an environment variable, if I'm correct. I know there are apps and frameworks that let you read a `.env` automatically, but afaik that's not Caddy's behavior. So I think you need to source it before starting Caddy.

**Comment by hslatman** [comment]
OK, I found you can run it with `--envfile .env`, which loads the environment variables into the process. That part seems to work if I run it as `caddy run --config Caddyfile --envfile .env --environ`, which prints the bouncer key. But I think the intention is for `{env.CROWDSEC_BOUNCER_KEY}` to also work? Not sure yet why that's not the case.

**Comment by hslatman** [comment]
Fixed in https://github.com/hslatman/caddy-crowdsec-bouncer/pull/28. 

The PR adds support for replacing `{env.<variable>` with the contents from the process environment variables at runtime. I think the main use case for this type of environment variable loading is when you intend to run Caddy somewhere different from where the Caddyfile is created/validated/adapted?

This still requires the `.env` file to be loaded before the process starts by sourcing it, or by providing the `--environ` flag. The `{env.<variable>} isn't read automatically from the `.env` file if it is present.

**Comment by doums** [comment]
@hslatman thx again!

> OK, I found you can run it with --envfile .env, which loads the environment variables into the process. That part seems to work if I run it as caddy run --config Caddyfile --envfile .env --environ, which prints the bouncer key and starts the server. But authentication still fails that way. But I think the intention is for {env.CROWDSEC_BOUNCER_KEY} to also work? Not sure yet why that's not the case.

Yes exactly that. Sorry it was not clear in my post, but I was referring to a docker setup with the environment variables loaded from an `.env` file:

```yaml
    environment:
      EMAIL: ${EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
      CROWDSEC_BOUNCER_KEY: ${CROWDSEC_BOUNCER_KEY}
      ACME_AGREE: 'true'
```

And so we could use the `{env.*}` notation in caddy config file
