### ISSUE TITLE
no API calls to pull decisions list after startup

### ISSUE THREAD

**Issue by doums** [hslatman/caddy-crowdsec-bouncer#26]
Hi, I just spotted that caddy bouncer only makes one API call to pull decisions list (`GET /v1/decisions/stream?startup=true`), during startup sequence and that's it. After that initial call, there is no other calls made to the API. I'm wondering if this is the intended behavior?
In comparison, `cs-firewall-bouncer` is calling to `/v1/decisions/stream` at the regular interval set in its config.

It's like `ticker_interval` value is not used at all.

![image](https://github.com/hslatman/caddy-crowdsec-bouncer/assets/6359431/dc0bfc57-b644-4291-8144-2c2290b315b6)

This is the crowdsec block I use in Caddyfile
```
  crowdsec {
    api_url http://host.docker.internal:8080
    api_key xxx
    ticker_interval 15s
    # disable_streaming
    # enable_hard_fails
  }
  order crowdsec first
```

Note: If I run in no-streaming mode (enabling `disable_streaming`) caddy calls the API as expected for each received request.

**Comment by hslatman** [comment]
Hey @doums, thank you for reporting this! Apparently the context for the background retrieval was cancelled too early, resulting in only the first retrieval working. I think I may have introduced that bug in the previous release, when I also upgraded the https://github.com/crowdsecurity/go-cs-bouncer library, and failed to properly check the runtime to continue running with the new logic.

**Comment by doums** [comment]
Happy helping to find bugs, and thanks for the quick fix ;)
