### ISSUE TITLE
I cant make it work

### ISSUE THREAD

**Issue by 9acca9** [hslatman/caddy-crowdsec-bouncer#44]
Hi.
Im trying to use this bouncer.
I install it, also crowdsec, enroll the server, etc.
I see this in crowdsec:
![image](https://github.com/hslatman/caddy-crowdsec-bouncer/assets/25393371/dccebb9d-2ffd-427a-a429-899d9a810c08)

So, it seems crowdsec is fine.
I compile with xcaddy and also seems working:
caddy list-modules result:

```
  Standard modules: 106

crowdsec

  Non-standard modules: 1
```

I put this in  my Caddyfile:
```
{
    crowdsec {
        api_url http://localhost:8080
        api_key 3xxx6xxxxxxxxxxxxxxxxx3fd
        ticker_interval 15s
        #disable_streaming
        #enable_hard_fails
    }

}

trilium.xxxxxxxxx.xyz {
        reverse_proxy crowdsec 192.168.0.10:8080

        log {
        output file /var/log/caddy/trilium-access.log {
        roll_size 10mb
        roll_keep 20
        roll_keep_for 720h
  }
}
}

```

But... when try to access i get an error:
`{"level":"error","ts":1716596310.84049,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"185.23.45.80","remote_port":"53294","client_ip":"185.23.45.80","proto":"HTTP/2.0","method":"GET","host":"trilium.xxxxxx.xyz","uri":"/","headers":{"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"],"Sec-Fetch-Dest":["document"],"Sec-Ch-Ua-Mobile":["?0"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"],"Sec-Fetch-Site":["none"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Sec-Ch-Ua":["\"Not-A.Brand\";v=\"99\", \"Chromium\";v=\"124\""],"Sec-Ch-Ua-Platform":["\"Linux\""],"Accept-Language":["en-US,en;q=0.9"],"Priority":["u=0, i"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"trilium.xxxxxxxx.xyz"}},"bytes_read":0,"user_id":"","duration":0.004853857,"size":0,"status":502,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"]}}`

Hope you can help me.
Thanks!

**Comment by Lipown** [comment]
See my part of Caddyfile. Working flawless:

```
photos.{$MY_DOMAIN} {
        route {
                crowdsec
                reverse_proxy http://192.168.0.51:2283
        }
        import logging
}
```
you should specify route so it goes thru Crowdsec first. Your transcript uses load balancer instead.

**Comment by morikplay** [comment]
I have the same issue as @9acca9 wrt `crowdsec` keyword without options, when listed in `route`

**Comment by 9acca9** [comment]
@morikplay if you find what is not working, please share the solution.
Thanks

**Comment by 9acca9** [comment]
@morikplay 
Well, maybe i found the problem for me.
I creater the caddy file with xcaddy and when i list the modules i just was getting this:
```
 Standard modules: 106

crowdsec

  Non-standard modules: 1
```

I download now the module from here https://caddyserver.com/download?package=github.com%2Fhslatman%2Fcaddy-crowdsec-bouncer

and now i get this:
```
  Standard modules: 121

caddy.listeners.layer4
crowdsec
http.handlers.crowdsec
layer4
layer4.matchers.crowdsec
layer4.matchers.ip
layer4.matchers.local_ip

  Non-standard modules: 7
```
And i can configure the route, and all look fine. But, i just make this like... some 5 minutes ago, so i need to verify if all is working. But it seems it is.
So, maybe this help you too.
Good luck!

**Comment by morikplay** [comment]
@9acca9. Thank you for the hints on modules. I can perhaps hazard a guess. I built mine w/ the following:
```
caddy.logging.encoders.formatted
caddy.logging.encoders.transform
crowdsec
http.handlers.rate_limit

  Non-standard modules: 4
```

And noticed that yours has few others with `crowdsec` namely `http.handlers` and `layer4.matchers`. I'll re-build w/ these to see whether it helps. If so, perhaps there may be room for improvement in this modules' documentation wherein dependent modules can be highlighted (or auto-pulled during build). I'll report back shortly.

**Comment by 9acca9** [comment]
Excellent!

**Comment by DJKatastrof** [comment]
I have the same issue. What's the solution here?

**Comment by DJKatastrof** [comment]
I figured it out later. Now I got these 
Are these enough/right?

![Image](https://github.com/user-attachments/assets/6eaae014-599e-49fc-9ee6-e5dd39fd191b)

**Comment by hslatman** [comment]
Yes, that looks as expected.

**Comment by DJKatastrof** [comment]
Coolt. Should this work with ipv6 as well?
