### ISSUE TITLE
Not a registered Caddy module package path

### ISSUE THREAD

**Issue by Unspec7** [hslatman/caddy-crowdsec-bouncer#53]
HTTP 400: github.com/hslatman/caddy-crowdsec-bouncer/crowdsec is not a registered Caddy module package path

Pretty self explanatory. Please register this module as a Caddy module so users can build with add-package

**Comment by hslatman** [comment]
@Unspec7 I'm going to close this issue for now. Feel free to (re)open a new issue issue if you'd like to discuss the splitting of modules for a cleaner process when using `caddy add-package github.com/hslatman/caddy-crowdsec-bouncer`
