### ISSUE TITLE
L4 Caddyfile support

### ISSUE THREAD

**Issue by ayykamp** [hslatman/caddy-crowdsec-bouncer#54]
Now that caddy-l4 [support Caddyfile config](https://github.com/mholt/caddy-l4?tab=readme-ov-file#config-examples), it would be very nice to also be able to configure the crowdsec bouncer in it.

Thanks :)

**Comment by ayykamp** [comment]
Currently a config like this:
```Caddyfile
{
	layer4 {
		0.0.0.0:1234 {
			@crowdsec crowdsec
			route @crowdsec {
				echo
			}
		}
	}
}
```

produces: `Error: adapting config using caddyfile: parsing caddyfile tokens for 'layer4': module layer4.matchers.crowdsec is not a Caddyfile unmarshaler; is *layer4.Matcher, at Caddyfile`

**Comment by hslatman** [comment]
https://github.com/hslatman/caddy-crowdsec-bouncer/releases/tag/v0.7.1 was released with support for Caddyfile configuration when using `layer4`. Your example config worked in my local testing. There's some work to be done in terms of testing and documentation, but you should be able to start using it now.
