### ISSUE TITLE
Possible multi-node problem with streaming

### ISSUE THREAD

**Issue by websitesca** [hslatman/caddy-crowdsec-bouncer#55]
Thanks for this awesome component!

We've noticed a problem with the "streaming" mode with multiple nodes, basically some decisions don't get picked up (adds and deletes). Everything works great in "live" mode, but there's a problem with "streaming" mode.

For example, say there are 2 nodes, A and B (each communicates with 1 LAPI on another server). If I block my own IP on the LAPI, I will see a debug log entry on A that the IP was added, but won't see it on node B.

(Also the number of entries was less than your `maxNumberOfDecisionsToLog` variable, so I know it should be logged)

Then to make matters even worse. If I delete my IP from the decisions on the LAPI, I may see the delete on node B but not A.

Thus the IP stays blocked on A and was never blocked on B, which is not good.

Took a peak in your code and I see this all relies a lot on `github.com/crowdsecurity/go-cs-bouncer` and so maybe the problem is there? Didn't see any error messages in the debug logs. Another place I saw was perhaps in your `startProcessingDecisions` method where you're handling the decisions, but couldn't see any race condition or way that the adds/deletes don't get processed or some log message is emitted.

If I restart the caddy container, it immediately gets the right data.

And I can see lots of other decisions (adds and deletes) constantly streaming to both servers so I know the nodes are communcating with the LAPI correctly.

Just wondering if you noticed this problem and if you knew of solutions? If you had ideas about where to look that would be great. Would be happy to work on a PR, but it seems likely that I should reach out to `github.com/crowdsecurity/go-cs-bouncer`. Thanks!

**Comment by websitesca** [comment]
Boom, simple as that https://github.com/crowdsecurity/go-cs-bouncer/issues/47

**Comment by hslatman** [comment]
Hey @websitesca,

Was about to suggest the same thing, but great that it got solved 🙂
