### ISSUE TITLE
Unable to build Caddy with Plugin

### ISSUE THREAD

**Issue by ducky710** [hslatman/caddy-crowdsec-bouncer#6]
Hi I've been trying to get this plugin to build with xcaddy in docker but to no avail.

It fails no matter what I do.

My dockerfile is as such

```
FROM caddy:2.4.3-builder-alpine AS builder

RUN xcaddy build \
    --with github.com/ueffel/caddy-brotli \
    --with github.com/mholt/caddy-dynamicdns \
    --with github.com/hslatman/caddy-crowdsec-bouncer/http \
    --with github.com/caddyserver/caddy/v2/cmd \
    --with github.com/caddyserver/caddy/v2/modules/standard \
    --with github.com/hslatman/caddy-crowdsec-bouncer/layer4 \
    --with github.com/caddy-dns/cloudflare

FROM caddy:2.4.3-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
I've tried as well just using these two but they failed as well so i tried with all 4 of the components but it made no difference.
--with github.com/hslatman/caddy-crowdsec-bouncer/layer4
--with github.com/hslatman/caddy-crowdsec-bouncer/http

This is the build error I receive.

```
2021/08/18 20:00:05 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /usr/bin/caddy -ldflags -w -s -trimpath
# github.com/hslatman/caddy-crowdsec-bouncer/crowdsec
/go/pkg/mod/github.com/hslatman/caddy-crowdsec-bouncer@v0.0.0-20210812151539-cb49bb94a241/crowdsec/crowdsec.go:44:37: cannot use parseCaddyfileGlobalOption (type func(*caddyfile.Dispenser) (interface {}, error)) as type httpcaddyfile.UnmarshalGlobalFunc in argument to httpcaddyfile.RegisterGlobalOption
2021/08/18 20:00:34 [INFO] Skipping cleanup as requested; leaving folder intact: /tmp/buildenv_2021-08-18-1958.477867331
2021/08/18 20:00:34 [FATAL] exit status 2
The command '/bin/sh -c xcaddy build     --with github.com/ueffel/caddy-brotli     --with github.com/mholt/caddy-dynamicdns     --with github.com/hslatman/caddy-crowdsec-bouncer/http     --with github.com/caddyserver/caddy/v2/cmd     --with github.com/caddyserver/caddy/v2/modules/standard     --with github.com/hslatman/caddy-crowdsec-bouncer/layer4     --with github.com/caddy-dns/cloudflare' returned a non-zero code: 1
```

**Comment by ducky710** [comment]
I've also just now tried  
```
--with github.com/mholt/caddy-l4 \
    --with github.com/caddyserver/format-encoder \
    --with github.com/hslatman/caddy-crowdsec-bouncer/http@main \
    --with github.com/hslatman/caddy-crowdsec-bouncer/layer4@main
```
from the dockerfile here in your repo but it still fails

**Comment by ducky710** [comment]
Lastly I tried the reverse of that^ and copied my additional plugins into your Dockerfile and it fails once more.

**Comment by hslatman** [comment]
It looks like a function signature related to Caddyfile parsing changed between Caddy versions recently. I've added that logic a couple of days ago, but apparently used an old version of Caddy to test it. Will have a look at it.

**Comment by ducky710** [comment]
Ah I see, Unfortunately I'm only familiar with Caddyfile configuration so I'll have to wait until theres a fix.

**Comment by hslatman** [comment]
I've upgraded to Caddy 2.4.3 and require Go 1.16 now for builds. There was indeed a change in the interface for parsing global Caddyfile options. It should've been fixed now.

**Comment by hslatman** [comment]
To be complete: using a Caddyfile for configuration is currently only supported for the HTTP handler. If you want to use the Layer4 handler to block on the TCP or UDP level, this can currently only be configured using JSON, because the Layer4 app itself has no support for configuration through Caddyfile yet. I saw that you had the import for this in your examples (`github.com/hslatman/caddy-crowdsec-bouncer/layer4`), so I figured you might be using it. If you don't need it, you can drop it from your builds, of course.

**Comment by ducky710** [comment]
Hey thanks a lot I appreciate the quick fix. I'm going to give it a go now. I actually only need HTTP support so I will drop that! Cheers
