### ISSUE TITLE
Issue while adding Go module

### ISSUE THREAD

**Issue by QJoly** [hslatman/caddy-crowdsec-bouncer#8]
Hi, 
I can't add the go package/module on my Linux server (debian 10) 
Go version :  go1.11.6 linux/amd64
```
root@Caddy:~# go get github.com/hslatman/caddy-crowdsec-bouncer/http
package crypto/ed25519: unrecognized import path "crypto/ed25519" (import path does not begin with hostname)
```

Thanks :)

**Comment by hslatman** [comment]
Hey @QJoly, I think it's due to the version of Go you use. Can you try it with Go 1.16 (or higher)?
